version: "3.9"

services:
  proxy:
    image: mitmproxy/mitmproxy
    volumes:
      - ./data:/home/mitmproxy/.mitmproxy
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      TZ: Europe/Vienna
    entrypoint: '/bin/sh -c "stty rows 24 cols 80 && mitmweb --web-host 0.0.0.0"'
    tty: true
    stdin_open: true
    networks:
      subnet:
        ipv4_address: 10.9.7.183

networks:
  subnet:
    external: true
    name: twentyfour

