services:
  dotoneserver:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      twentyfour:
        ipv4_address: 10.9.7.1

networks:
  twentyfour:
    name: twentyfour
    driver: ipvlan
    ipam:
      config:
        - subnet: 10.9.7.0/24
          gateway: 10.9.7.254
    driver_opts:
      parent: ens18
      ipvlan_mode: l2
