services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      TZ: Europe/Vienna
      WEBPASSWORD: jfl-pihole
      DNSMASQ_LISTENING: all
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      subnet:
        ipv4_address: 10.9.7.179

networks:
  subnet:
    external: true
    name: twentyfour
